Databases week2
faheem102/hyf-homework pull request #16
Opened 2022-02-11 11:14 UTC by faheem102

2022-02-11 12:24 UTC, mani-zaeim commented
Well done, Good job

2022-02-11 13:52 UTC, faheem102 commented on databases/week2/hyf_lesson02queries.sql
> +AND task.status_id = 1;
Hi mani thanx for your feedback. Please see my new commit file where i made the change from status_id to status.

2022-02-12 16:19 UTC, martamatos commented on databases/week2/book_author.sql
> +  `award_id` int(10) unsigned NOT NULL,
one book can only have one award?

2022-02-12 16:30 UTC, martamatos requested changes
Good work overall! Left only some small comments xD

2022-02-12 16:30 UTC, martamatos commented on databases/week2/book_author.sql
> +  `award_date` DATETIME NULL DEFAULT NULL
you can also use `DATE` type, as you probably don't need to know the time

2022-02-12 16:30 UTC, martamatos commented on databases/week2/book_author.sql
> +  `award_id` int(10) unsigned NOT NULL,
one book can only have one award?

2022-02-12 16:30 UTC, martamatos commented on databases/week2/hyf_lesson02queries.sql
> +insert into task (id, title, description, created, updated, due_date, status_id) values (36, 'Complete the Assignment', 'work on your recent hyf assignment', '2022-02-06 06:54:16', '2022-02-07 13:05:
you don't need to insert the `id`, and it's actually better not to insert it and let mysql auto increment it.

2022-02-12 16:30 UTC, martamatos commented on databases/week2/hyf_lesson02queries.sql
> +SELECT *
how can i see the titles of the tasks?

2022-02-12 16:30 UTC, martamatos commented on databases/week2/school_database.sql
> +  `begins` DATETIME NULL DEFAULT NULL,
a `DATE` type here would be enough since you probably don't need to know the time

2022-02-12 16:30 UTC, martamatos commented on databases/week2/school_database.sql
> +) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
where is the definition of the foreign key? ;p

2022-02-12 16:31 UTC, martamatos commented
Sorry @mani-zaeim , i didn't notice you had already reviewed this :/

2022-02-20 14:00 UTC, merged