Nodejs week1
faheem102/hyf-homework pull request #18
Opened 2022-02-26 21:54 UTC by faheem102

2022-03-02 23:01 UTC, STEP0HEN requested changes
Great Job @faheem102. 
Very nice and thoughtful that you're making it a habit to comment your code, keep it up.
Also very good with the console.logs,  which implies you're testing your code but never push console.logs, always remember to remove them when you're done testing.

I left a few comments for things to change or improve on, let me know if something isn't clear.

Awesome job done. 💯

2022-03-02 23:05 UTC, STEP0HEN commented on nodejs/week1/src/backend/app.js
> +const app = express();
did you mean to say express.Router() here?

2022-03-03 13:32 UTC, faheem102 commented on nodejs/week1/src/backend/app.js
> +  const randomMeal = allMealswithReviews[Math.floor(Math.random()* allMealswithReviews.length)];
I have made a separate random number generator function and used it twice to get random meal and reservation.

2022-03-03 13:32 UTC, faheem102 commented on nodejs/week1/src/backend/server.js
> +});
this actually came as template given by Orhan. I was not sure if I can modify it in anyway.

2022-03-03 13:32 UTC, faheem102 commented on nodejs/week1/src/backend/app.js
> +});
I have removed this extra line of code and got the response from reservations

2022-03-03 13:32 UTC, faheem102 commented on nodejs/week1/src/backend/app.js
> +});
I have modified my code here now its showing me each meal with its relevant review. please have a look at my new commit which contains all the new changes you have suggested. thank you

2022-03-04 18:32 UTC, STEP0HEN commented
Hi Faheem, great that you've made the changes but I think you missed adding the node_modules to your .gitignore so I can't really go past that to see the changes you made because there 1000's of files for me to scroll through to get to the actual change you made.

Do that and push again and I'll look at the changes you made.

2022-03-04 19:33 UTC, faheem102 commented
> Hi Faheem, great that you've made the changes but I think you missed adding the node_modules to your .gitignore so I can't really go past that to see the changes you made because there 1000's of files for me to scroll through to get to the actual change you made.
> 
> Do that and push again and I'll look at the changes you made.

hi Stephen i put the node_modules files then commit and push but its not showing anything in the commit. how can I commit and push the same files ????

2022-03-04 19:35 UTC, faheem102 commented
> > Hi Faheem, great that you've made the changes but I think you missed adding the node_modules to your .gitignore so I can't really go past that to see the changes you made because there 1000's of files for me to scroll through to get to the actual change you made.
> > Do that and push again and I'll look at the changes you made.
> 
> hi Stephen i put the node_modules files then commit and push but its not showing anything in the commit. how can I commit and push the same files ????

I push to the branch many times. it says everything is up to date.

2022-03-04 20:02 UTC, STEP0HEN approved these changes
Thanks for the node modules.
I approved the PR, revert the server js code and you can merge

2022-03-04 20:02 UTC, STEP0HEN commented on nodejs/week1/src/backend/app.js
> +});
Actually, let this be separated in the server.js. Revert this change and you can merge the PR.

2022-03-04 20:18 UTC, faheem102 commented
I have same problem Stephen and I spent more than enough time to find a solution to this I can't  sort out what to do.

2022-03-04 20:33 UTC, merged